# Generated by Django 4.2 on 2026-05-23 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('razonSocial', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('fechaRegistro', models.DateField(default=datetime.date.today)),
                ('estado', models.CharField(max_length=100)),
                ('plan_suscripcion_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
