# Generated by Django 6.0.5 on 2026-05-06 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('severidad', models.CharField(max_length=100)),
                ('mensaje', models.CharField(max_length=500)),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
                ('fechaLectura', models.DateField(auto_now=True)),
                ('estado', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.empresa', verbose_name='empresaAlerta')),
            ],
        ),
    ]
