# Generated by Django 4.2 on 2026-05-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('severidad', models.CharField(max_length=100)),
                ('mensaje', models.CharField(max_length=500)),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
                ('fechaLectura', models.DateField(auto_now=True)),
                ('estado', models.CharField(max_length=100)),
                ('usuario_id', models.IntegerField(blank=True, null=True)),
                ('empresa_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
