# Generated by Django 6.0.5 on 2026-05-06 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0001_initial'),
        ('recursoCloud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('moneda', models.CharField(max_length=10)),
                ('servicioCloud', models.CharField(max_length=100)),
                ('unidadMedida', models.CharField(max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=14)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyecto.proyecto', verbose_name='proyecto')),
                ('recursoCloud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursoCloud.recursocloud', verbose_name='recursoCloud')),
            ],
        ),
    ]
