# Generated by Django 4.2 on 2026-05-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('moneda', models.CharField(max_length=10)),
                ('servicioCloud', models.CharField(max_length=100)),
                ('unidadMedida', models.CharField(max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=14)),
                ('recursoCloud_id', models.IntegerField(blank=True, null=True)),
                ('proyecto_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
