# Generated by Django 4.2 on 2026-05-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=200)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('ipOrigen', models.CharField(max_length=100)),
                ('detalles', models.CharField(max_length=200)),
                ('resultado', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='registroauditoria',
            index=models.Index(fields=['accion'], name='idx_audit_accion'),
        ),
        migrations.AddIndex(
            model_name='registroauditoria',
            index=models.Index(fields=['resultado'], name='idx_audit_resultado'),
        ),
        migrations.AddIndex(
            model_name='registroauditoria',
            index=models.Index(fields=['usuario'], name='idx_audit_usuario'),
        ),
    ]
