# Generated by Django 4.2 on 2026-05-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoCloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_id', models.IntegerField(db_index=True)),
                ('empresa_nombre', models.CharField(max_length=100)),
                ('proveedor', models.CharField(max_length=20)),
                ('servicio', models.CharField(max_length=100)),
                ('costo', models.DecimalField(decimal_places=4, max_digits=12)),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('fechaGeneracion', models.DateField(auto_now_add=True)),
                ('periodoInicio', models.DateField()),
                ('periodoFin', models.DateField()),
                ('formato', models.CharField(max_length=50)),
                ('usuario_id', models.IntegerField(blank=True, null=True)),
                ('empresa_id', models.IntegerField(blank=True, null=True)),
                ('proyecto_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='consumocloud',
            index=models.Index(fields=['empresa_id', 'anio', 'mes'], name='idx_consumo_lookup'),
        ),
    ]
