# Generated by Django 6.0.5 on 2026-05-06 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoCloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_id', models.IntegerField(db_index=True)),
                ('empresa_nombre', models.CharField(max_length=100)),
                ('proveedor', models.CharField(max_length=20)),
                ('servicio', models.CharField(max_length=100)),
                ('costo', models.DecimalField(decimal_places=4, max_digits=12)),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['empresa_id', 'anio', 'mes'], name='idx_consumo_lookup')],
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('fechaGeneracion', models.DateField(auto_now_add=True)),
                ('periodoInicio', models.DateField()),
                ('periodoFin', models.DateField()),
                ('formato', models.CharField(max_length=50)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.empresa', verbose_name='empresa')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyecto.proyecto', verbose_name='proyecto')),
            ],
        ),
    ]
