# Generated by Django 4.2 on 2026-05-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoCloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('tamano', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
                ('etiquetas', models.CharField(blank=True, max_length=200)),
                ('cuentaCloud_id', models.IntegerField(blank=True, null=True)),
                ('proyecto_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
