# Generated by Django 6.0.5 on 2026-05-06 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentaCloud', '0001_initial'),
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoCloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('tamano', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
                ('etiquetas', models.CharField(blank=True, max_length=200)),
                ('cuentaCloud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuentaCloud.cuentacloud', verbose_name='cuentaCloud')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyecto.proyecto', verbose_name='proyecto')),
            ],
        ),
    ]
