# Generated by Django 6.0.5 on 2026-05-06 22:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planSuscripcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('razonSocial', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('fechaRegistro', models.DateField(default=datetime.date.today)),
                ('estado', models.CharField(max_length=100)),
                ('plan_suscripcion', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planSuscripcion.plansuscripcion')),
            ],
        ),
    ]
